openapi: 3.0.0
info:
  version: 0.4.0
  title: Recordream API docs
  description: 드리미들의 API 문서입니다
  license:
    name: MIT
servers:
  - url: 'http://localhost:8000'
  - url: 'http://13.125.138.47:8000'
tags:
  - name: Records
    description: Record resource APIs
  - name: Voices
    description: Voice resource APIs
  - name: Auth
    description: Authorization APIs
  - name: User
    description: User resource APIs
paths:
  '/record/{recordId}':
    get:
      tags:
        - Records
      summary: Returns record
      description: |
        Return a single instance of a record.
      parameters:
        - name: recordId
          description: 꿈 기록 고유 ID
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: objectId
            example: 62d7b6f19669f53b6c72a89f
      responses:
        '200':
          description: 꿈 기록 조회 성공
          content:
            application/json:
              schema:
                properties:
                  record:
                    $ref: '#/paths/~1record/get/responses/200/content/application~1json/schema/properties/record'
              example:
                status: 200
                success: true
                message: 꿈 기록 조회 성공
                data:
                  _id: 62d7b6f19669f53b6c72a89f
                  writer: 레코드림
                  date: 2022/07/04 (월)
                  title: 병원에서 죽을 뻔 했음 ㄷㄷ
                  voice: null
                  content: '오늘 꿈꿨는데 얼마나 무서웠는지 깬 이후로 이 시간까지 하나도 안까먹음. 거의 스릴러 영화같은 연출이었음. 배경은 병원이었는데, 너무 내부가 이쁜거야. 막 엄청 큰 통유리로 둘러쌓여있고 창 밖에 자연경치도 장난아니고. 근데 약간 요양원에 계실거같은 할머니 할아버지들이 많긴 했음. 그래서 친구랑 왜인지는 모르겠지만 거기에 딱 들어갔는데, 병원 입구쪽에 어떤 젊은 여자가 휠체어에 타고있었고, 간호사가 그 사람 데리고 어두운 방으로 들어가는게  보였음. 거기서 부터 좀 쎄했다... 그때 뛰쳐나갔어야했는데;; 그래서 보니까 원래 끝쪽 복도에그 여자분이 탄 상태로 휠체어가 끝만 보이게 걸쳐져있었는데 그게 확 사라진거임. 알고보니 그분이 병원 사람들한테  살해당해서 사라진거.. (장기매매, 해부 이런거였음..) 그래서 나랑 내 친구도 끌려가기 직전이었는데, 거기서 딱 타임리프가 되어서 다시 병원 처음 들어가는 순간으로 이동되었음. 근데 친구는 타임리프된거 모르는거같고 나도 꿈인가? 싶었는데 데자뷰처럼 이번에는 다른 여자분이 휠체어타고 검은 방으로 이동되고있는거야. 그래서 머리 탁 맞은거처럼 소름돋아서 간호사들 앞에서는 모르는 척 하다가 나중에 친구 데리고 밖으로 도망나왓음. 근데 거기 병원 간호사랑 의사들이 우리 잡을라고 막 몇키로를 달리고 우린 도망갈라고 미친듯이 뛰고.. 근데 또 서울 번화가 느낌이 아닌 좀 시골 스탈이어서 어디 도망갈데도 없고.. 그러다가 깼네요… '
                  emotion: 2
                  dream_color: 3
                  genre:
                    - 4
                    - 5
                  note: 결론은 너무 무서웠다..~
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
    patch:
      tags:
        - Records
      summary: Update record
      description: |
        Update a record.
      parameters:
        - $ref: '#/paths/~1record~1%7BrecordId%7D/get/parameters/0'
      responses:
        '200':
          description: 꿈 기록 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: 꿈 기록 수정 성공
        '400':
          description: '제목 오류 또는 음성/작성자 수정 시도 or 감정, 색깔, 장르 범위 오류입니다'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 400
                success: false
                message: '제목 오류 또는 음성/작성자 수정 시도 or 감정, 색깔, 장르 범위 오류입니다'
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
    delete:
      tags:
        - Records
      summary: Delete record
      description: |
        Delete a record.
      parameters:
        - $ref: '#/paths/~1record~1%7BrecordId%7D/get/parameters/0'
      responses:
        '204':
          description: No content.
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /record:
    get:
      tags:
        - Records
      summary: Home(list)
      description: |
        Home
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      responses:
        '200':
          description: 꿈 기록 목록(홈) 조회 성공
          content:
            application/json:
              schema:
                properties:
                  record:
                    type: object
                    required:
                      - _id
                      - date
                      - title
                      - writer
                    properties:
                      _id:
                        type: string
                      writer:
                        type: string
                      date:
                        type: string
                        format: date
                      title:
                        type: string
                      voice:
                        type: object
                      content:
                        type: string
              example:
                status: 200
                success: true
                message: 꿈 기록 목록(홈) 조회 성공
                data:
                  nickname: 레코드림
                  records:
                    - _id: 63727b78afcf86c942603076
                      emotion: 4
                      date: 2022/11/15 TUE
                      title: 오늘은 11월 15일
                      genre:
                        - 1
                      content: content1
                    - _id: 63825833908603b09f0ee050
                      emotion: 4
                      date: 2019/01/01 TUE
                      title: 준호랑 수연이랑
                      genre:
                        - 1
                        - 3
                        - 5
                      content: 줌으로 회의했는데 둘이 나 중학생때 살던 집 할머니 방 같은데에 같이 있었다;; 자세히 기억은 안나는데 어느순간 나도 같이 있었고 새로운 스터디 방향 얘기를 하다가 의견이 안 맞아서 애들이랑 도시락 싸려고 했는데 백종원 아저씨가 나와서 자기가 도시락 싸는법 가르쳐 준다함
                    - _id: 638257ca908603b09f0ee04c
                      emotion: 2
                      date: 2022/08/26 FRI
                      title: 꿈에 예리 나왔음
                      genre:
                        - 4
                        - 5
                      content: 우리집에서 같이 자고 일어났는데 걔가 대만 가고 싶다고 하는거임 그래서 나 갔다왔는데 너무 좋앆다고 하다가 즉흥적으로 같이 비행기 바로 끊는데 예리는 그 전에 다른 친구랑 싱가포르 가기로 했었어서 거기서 바로 온다고 했고 스카이라이너로 예매하길래 오… 연예인도 이런거 쓰는구나 싶어서 신기하다고 생각하다가 깼음
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
    post:
      tags:
        - Records
      summary: Create a record
      description: Create a record
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - date
                - writer
              properties:
                date:
                  type: string
                  format: date-time
                title:
                  type: string
                content:
                  type: string
                emotion:
                  type: number
                genre:
                  type: array
                  items:
                    type: number
                note:
                  type: string
                voice:
                  type: string
              example:
                data:
                  title: 오늘은 7월 20일
                  date: '2022-07-22T11:14:49.196'
                  content: 귀엽다
                  emotion: 2
                  genre:
                    - 1
                    - 2
                    - 5
                  note: null
                  voice: 62cdb868c3032f2b7af76531
      responses:
        '201':
          description: 꿈 기록 작성 성공
          content:
            application/json:
              schema:
                properties:
                  record_id:
                    type: object
                    required:
                      - _id
                    properties:
                      _id:
                        type: string
              example:
                status: 201
                success: true
                message: 꿈 기록 작성 성공
                data:
                  _id: 62cfc9f8e9ce27c134401f70
        '400':
          content:
            application/json:
              examples:
                제목이 비어있거나 길이 초과:
                  value:
                    status: 400
                    success: false
                    message: 제목이 없거나 길이를 초과하였습니다.
                '감정, 장르 범위 오류':
                  value:
                    status: 400
                    success: false
                    message: '감정, 장르 범위 오류입니다.'
                날짜 포맷이 틀림:
                  value:
                    status: 400
                    success: false
                    message: 날짜 포맷이 틀립니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /record/storage/list?filter=:
    get:
      tags:
        - Records
      summary: Storage(list)
      description: |
        Storage(list)
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
        - name: filter
          description: 조회할 감정(0~6)
          in: query
          required: true
          style: simple
          explode: false
          schema:
            type: int
            example: 2
      responses:
        '200':
          description: 꿈 기록 목록(보관함) 조회 성공
          content:
            application/json:
              schema:
                properties:
                  record:
                    $ref: '#/paths/~1record/get/responses/200/content/application~1json/schema/properties/record'
              example:
                status: 200
                success: true
                message: 꿈 기록 목록(보관함) 조회 성공
                data:
                  records_count: 2
                  records:
                    - _id: 62d16f41e8b4508dbca5eaf4
                      emotion: 2
                      date: 2022/06/26 SUN
                      title: 오늘 친구들이랑 피자 먹고 진짜 재밌는 일이 많은 꿈을 꿨다.
                      genre:
                        - 1
                        - 2
                        - 5
                    - _id: 638222560861027fe3e8b0c4
                      emotion: 2
                      date: 2022/11/26 SAT
                      title: 오늘은 11월 26일
                      genre:
                        - 3
                        - 4
        '400':
          description: 감정 범위(0~6) 벗어났을 경우
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 400
                success: false
                message: 감정 범위를 벗어났습니다.
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /record/storage/search?keyword=:
    get:
      tags:
        - Records
      summary: Search Keyword
      description: |
        Search Keyword
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
        - name: keyword
          description: 검색 키워드
          in: query
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 화이팅
      responses:
        '200':
          description: 꿈 기록 검색 성공
          content:
            application/json:
              schema:
                properties:
                  record:
                    $ref: '#/paths/~1record/get/responses/200/content/application~1json/schema/properties/record'
              example:
                status: 200
                success: true
                message: 꿈 기록 검색 성공
                data:
                  records_count: 2
                  records:
                    - _id: 62d32a47fc88f70097698fff
                      title: fighting_note2
                      date: 2023/07/15 (토)
                      emotion: 1
                      genre:
                        - 1
                        - 2
                        - 5
                    - _id: 62d32a41fc88f70097698ffd
                      title: 화이팅ㅇㅇ
                      date: 2023/07/16 (일)
                      emotion: 4
                      genre:
                        - 0
        '400':
          description: 필요한 값이 없습니다.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 400
                success: false
                message: 필요한 값이 없습니다.
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /auth/login:
    post:
      tags:
        - Auth
      summary: Social Login
      description: Social Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fcmToken
              properties:
                fcmToken:
                  type: string
              example:
                fcmToken: 'egcrkqdwh00bue-rambgzd:APA91bFtQBN4KOtUgxYHUb5lsqRIiKCNHm4GeAyGELccSFARJ9BRjpm9rCPmJPiYPybswKUXC799L_5o0oQhGLKSKDrYdznVFCkaUc3i0PaWDPBaBCdY5ajFNwTTngNG7jNGGmAkZLCh'
            examples:
              Kakao Login:
                value:
                  kakaoToken: example kakaoToken
                  fcmToken: 'egcrkqdwh00bue-rambgzd:APA91bFtQBN4KOtUgxYHUb5lsqRIiKCNHm4GeAyGELccSFARJ9BRjpm9rCPmJPiYPybswKUXC799L_5o0oQhGLKSKDrYdznVFCkaUc3i0PaWDPBaBCdY5ajFNwTTngNG7jNGGmAkZLCh'
              Apple Login:
                value:
                  appleToken: example appleToken
                  fcmToken: 'egcrkqdwh00bue-rambgzd:APA91bFtQBN4KOtUgxYHUb5lsqRIiKCNHm4GeAyGELccSFARJ9BRjpm9rCPmJPiYPybswKUXC799L_5o0oQhGLKSKDrYdznVFCkaUc3i0PaWDPBaBCdY5ajFNwTTngNG7jNGGmAkZLCh'
      responses:
        '200':
          content:
            application/json:
              examples:
                로그인(기존 유저):
                  value:
                    status: 200
                    success: true
                    message: 로그인 성공
                    data:
                      isAlreadyUser: true
                      accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjM1Yjk3N2VhNWZkZDU3YzdlYmI0YzdkIn0sImlhdCI6MTY3MjQyMDU2NiwiZXhwIjoxNjc0NzUzMzY2fQ.kYs0RxE3nfH-HRd2fTAlH-hYEXHkQXPHD0yETIFO-CY
                      refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzI0MjA1NjYsImV4cCI6MTY3NTAxMjU2Nn0.x3TV0F1XB16d0UvzM5ihPrNsC4InEMpjOsfdmNN0gMY
                      nickname: 레코드림
                회원가입(신규 유저):
                  value:
                    status: 200
                    success: true
                    message: 회원가입 성공
                    data:
                      isAlreadyUser: false
                      accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjM1Yjk3N2VhNWZkZDU3YzdlYmI0YzdkIn0sImlhdCI6MTY3MjQyMDU2NiwiZXhwIjoxNjc0NzUzMzY2fQ.kYs0RxE3nfH-HRd2fTAlH-hYEXHkQXPHD0yETIFO-CY
                      refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzI0MjA1NjYsImV4cCI6MTY3NTAxMjU2Nn0.x3TV0F1XB16d0UvzM5ihPrNsC4InEMpjOsfdmNN0gMY
                      nickname: 레코드림
        '400':
          content:
            application/json:
              examples:
                'kakaToken, appleToken 둘 다 존재':
                  value:
                    status: 400
                    success: false
                    message: 토큰 값은 하나이어야 합니다.
                'kakaoToken, appleToken 둘 다 없거나 fcmToken이 없음':
                  value:
                    status: 400
                    success: false
                    message: 필요한 값이 없습니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /auth/token:
    post:
      tags:
        - Auth
      summary: Refresh AccessToken
      description: Refresh AccessToken
      parameters:
        - name: access
          description: 액세스 토큰
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlkRmlyZWJhc2UiOm51bGwsImlhdCI6MTY0OTY3Nzg1MiwiZXhwIjoxNjQ5NzY0MjUyLCJpc3MiOiJoYXZpdCJ9.ik0zU_quZuTdOis9kSLkoXwM6pCz10uBbpjmcsVuf5
        - name: refresh
          description: 리프레시 토큰
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDk2Nzc4NTIsImV4cCI6MTY1MDg4NzQ1MiwiaXNzIjoiaGF2aXQifQ.Ehg_y2Kv3YT_IIPRATp14nbd6bFQxf00TlP61XbkxXA
      responses:
        '200':
          description: Access Token 재발급 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: Access Token 재발급 성공
                data:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjMzYjM4NjhjMjQ1YzkwNzhhMjQ0NGZlIn0sImlhdCI6MTY2NDg2MTY4NywiZXhwIjoxNjY0ODY1Mjg3fQ.2AboGVE9Gkdm5of861FLVLaZIWGPmGRIRDKaOcbzkbc
                  refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjQ4MjcxNzksImV4cCI6MTY2NjAzNjc3OX0.MZ63t_R2PWQqusAMiMPZMMcLlRqhY_qz9WTSVSnQ0Hk
        '400':
          description: accessToken이나 refreshToken이 없을 경우
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 400
                success: false
                message: 토큰이 없습니다.
        '401':
          content:
            application/json:
              examples:
                '유효하지 않은 accessToken, refreshToken':
                  value:
                    status: 401
                    success: false
                    message: 유효하지 않은 토큰입니다.
                'accessToken, refreshToken 둘 다 만료':
                  value:
                    status: 401
                    success: false
                    message: 'Access, Refresh Token 모두 만료되었습니다. 재로그인이 필요합니다.'
        '403':
          description: accessToken이 만료되지 않았을 경우
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 403
                success: false
                message: 아직 유효한 토큰입니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /auth/logout:
    patch:
      tags:
        - Auth
      summary: Social Logout
      description: 해당 유저를 로그아웃 처리합니다.
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1auth~1login/post/requestBody/content/application~1json/schema'
      responses:
        '200':
          description: 로그아웃 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: 로그아웃 성공
        '404':
          content:
            application/json:
              examples:
                fcmToken을 안 넣음:
                  value:
                    status: 404
                    success: false
                    message: 존재하지 않는 자원
                DB에 존재하지 않는 fcmToken:
                  value:
                    status: 404
                    success: false
                    message: 존재하지 않는 fcm Token 입니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /user:
    delete:
      tags:
        - User
      summary: Delete User
      description: Delete User
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      responses:
        '200':
          description: 회원탈퇴 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
              example:
                status: 200
                success: true
                message: 회원탈퇴 성공
        '400':
          content:
            application/json:
              examples:
                존재하지 않는 유저:
                  value:
                    status: 400
                    success: false
                    message: 필요한 값이 없습니다.
                이미 삭제된 유저:
                  value:
                    status: 400
                    success: false
                    message: 이미 삭제된 유저입니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
    get:
      tags:
        - User
      summary: Get User
      description: Get User
      parameters:
        - name: Authorization
          description: 유저 인증(Access Token)
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlkRmlyZWJhc2UiOm51bGwsImlhdCI6MTY0OTY3Nzg1MiwiZXhwIjoxNjQ5NzY0MjUyLCJpc3MiOiJoYXZpdCJ9.ik0zU_quZuTdOis9kSLkoXwM6pCz10uBbpjmcsVuf5
      responses:
        '200':
          description: 회원정보 조회 성공
          content:
            application/json:
              schema:
                properties:
                  user:
                    type: object
                    properties:
                      nickname:
                        type: string
                      email:
                        type: string
                      isActive:
                        type: Boolean
                      time:
                        type: string
              example:
                status: 200
                success: true
                message: 회원정보 조회 성공
                data:
                  nickname: 레코드림
                  email: recordream@gmail.com
                  isActive: true
                  time: 'PM 03:10'
        '404':
          description: 존재하지 않는 자원
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
              example:
                status: 404
                success: false
                message: 존재하지 않는 자원
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 500
                success: false
                message: 서버 내부 오류
  /user/nickname:
    put:
      tags:
        - User
      summary: Update User Nickname
      description: Update User Nickname
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
              properties:
                nickname:
                  type: string
              example:
                nickname: 레코드림 짱
      responses:
        '200':
          description: 닉네임 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: 닉네임 수정 성공
        '400':
          content:
            application/json:
              examples:
                request body 비어있음:
                  value:
                    status: 400
                    success: false
                    message: 닉네임 수정 실패
                닉네임 룰 지키지 않음:
                  value:
                    status: 400
                    success: false
                    message: '닉네임은 최소 1글자, 최대 8글자여야 합니다.'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /user/fcm-token:
    put:
      tags:
        - User
      summary: Refresh User's fcmToken
      description: Refresh User's fcmToken
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        description: 'originToken = 원래의 fcm Token, newToken = 변경할 fcm Token'
        content:
          application/json:
            schema:
              type: object
              required:
                - originToken
                - newToken
              properties:
                originToken:
                  type: string
                newToken:
                  type: string
              example:
                originToken: 'dCzOp-n2TELwmhENJ_TbfH:APA91bF7c3jNLxaU9rv8-rFYtwGlC8TO4HFMti8Vk9vfIZpZ613u3ok8e1G2z-AAq9niRpBwFzwQtiYxWvaz796W1PECezxu7dCs_Qy3z2Rerz7KO2wuMCINumfOZESSdxQrKz51MMV2'
                newToken: 'cxxvrsrJQEYFnLMW_YsQ9J:APA91bGXuwSX5XbgtZIwMsvBkCRJNib-ry--86YMTQdgm6-RR5qDnH7KcUJqauniPxhPmhtBP5bW5YzXlbGFecLFK8IbDQ7D7MQ_VW4JnJxFfxKyGig_t6lVqs8hmmdFynTGr3QkaLz1'
      responses:
        '200':
          description: fcm Token 갱신 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: fcm Token 갱신 성공
        '404':
          content:
            application/json:
              examples:
                존재하지 않는 유저:
                  value:
                    status: 404
                    success: false
                    message: 필요한 값이 없습니다.
                입력한 originToken이 DB에 없음:
                  value:
                    status: 404
                    success: false
                    message: 존재하지 않는 fcm Token 입니다.
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /user/toggle:
    patch:
      tags:
        - User
      summary: PushAlarm Toggle Change
      description: PushAlarm Toggle Change
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - isActive
              properties:
                isActive:
                  type: boolean
              example:
                isActive: true
      responses:
        '200':
          description: 푸시알림 토글 변경 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 200
                success: true
                message: 푸시알림 토글 변경 성공
                data:
                  isActive: true
        '400':
          description: request-body에 isActive 넣지 않았을 경우
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/get/responses/404/content/application~1json/schema'
              example:
                status: 400
                success: false
                message: 푸시알림 토글 변경 실패
        '500':
          $ref: '#/paths/~1user/get/responses/500'
  /user/notice:
    post:
      tags:
        - User
      summary: Save notice time
      description: Save notice time
      parameters:
        - $ref: '#/paths/~1user/get/parameters/0'
      requestBody:
        description: 'time 형식 반드시 "AM/PM 00:00" 이여야 합니다!!! (AM/PM 대문자여야 함)'
        content:
          application/json:
            schema:
              type: object
              required:
                - time
              properties:
                time:
                  type: string
              example:
                time: 'PM 03:10'
      responses:
        '201':
          description: 푸시알림 시간 저장 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1user/delete/responses/200/content/application~1json/schema'
              example:
                status: 201
                success: true
                message: 푸시알림 시간 저장 성공
        '400':
          content:
            application/json:
              examples:
                time 형식 지키지 않음:
                  value:
                    status: 400
                    success: false
                    message: 푸시알림 시간 저장 실패 (형식을 맞춰주세요.)
                토글 Off인데 시간 설정을 하려함:
                  value:
                    status: 400
                    success: false
                    message: 토글 Off시에는 시간을 설정할 수 없습니다.
        '404':
          $ref: '#/paths/~1user/get/responses/404'
        '500':
          $ref: '#/paths/~1user/get/responses/500'
components: null
